# Generated by Django 4.1.5 on 2023-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_food',
            new_name='Orderfood',
        ),
    ]
