# Generated by Django 4.1.5 on 2023-01-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_food_orderfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_field',
            new_name='deliver_finish',
        ),
    ]
